language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - tip
  - master

install:
  - go get -v github.com/mitchellh/gox

env:
  - PRIMARY_MIRROR="http://database.clamav.net"

script:
  - go test -v -short -race .
  - gox -verbose -parallel=2

notifications:
  email:
    on_success: change
    on_failure: change

matrix:
  allow_failures:
    - go: master, tip